spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083
